### ISSUE TITLE
单回波下时间延迟是100ms还是50ms?

### ISSUE THREAD

**Issue by gaoyuanhezhihao** [HesaiTechnology/Pandar40p_ros#5]
你好，我们的Pandar40p没接上时间同步，所以它自带的时间戳不对。我们用的是接收时间来估计其starttime,单回波，10Hz。想请问下接受时间和starttime大概差多少？

**Comment by trickyMan** [comment]
没有详细测试过，从内部的数据流程 + 网口延迟，应该是 2ms 左右。

**Comment by gaoyuanhezhihao** [comment]
那么这个包里最早的点的时间(starttime)和我主机接受到整个包的时间是不是单回波相差50ms?双回波100ms?

**Comment by trickyMan** [comment]
哦，你问的是这个啊。User Manual里面有时间的计算规则的。每次采样大概是50us左右，单回波模式下，最早的采样点和最晚的采样点相差 10次采样，大概540us左右（具体参考User Manual，其次这份代码里面也有这部分的参考代码）。双汇波则折半。

**Comment by trickyMan** [comment]
![image](https://user-images.githubusercontent.com/3348813/63069943-cdefad80-bf4b-11e9-8d85-16ff1fd30c0d.png)

**Comment by gaoyuanhezhihao** [comment]
那么单回波，一整圈72000个点收到后的时间与其中最早的点时间相差54ms左右？

**Comment by trickyMan** [comment]
0.2度一次采样，每圈1800次采样，每个包里面有10次采样（单回波），一共180个包，每一圈100ms（10hz），每个包555us（100ms/180）。所以根据采样截图算的是 55.56us。请问你是如何算得最终数据的？

**Comment by trickyMan** [comment]
再按照你的72000计算规则，72000/40 = 采样次数 = 1800次采样。360度/1800 = 0.2度。

**Comment by gaoyuanhezhihao** [comment]
也就是单回波收到10个Block，双回拨收到20个Block的时间都是一样的？对应的都是10次采样。只不过双回波下一个UDP的长度翻倍？

**Comment by trickyMan** [comment]
UDP长度不翻倍，而是分两个UDP包发送，可能你需要读一下User Manual和相应的处理代码。:)

**Comment by gaoyuanhezhihao** [comment]
![Screenshot from 2019-08-15 15-45-28](https://user-images.githubusercontent.com/11392359/63080623-220e8800-bf74-11e9-9ed3-0b702fab0098.png)
我们在lidarCallBack函数中减去了101ms作为这一圈点云的起始时间。但是感觉应该减去50ms才对

**Comment by trickyMan** [comment]
这里callback的timestamp表示的是这个点云的第一个点的时间戳。也可以从代码中有所体现。为什么需要-100ms？
