### ISSUE TITLE
Points quality is different on windows and linux machine 

### ISSUE THREAD

**Issue by murikill** [HesaiTechnology/Pandar40p_ros#7]
I'm using Pandar40p generally with ROS API and I'm not really happy with the points quality on my Ubuntu machine. The edges are not clearly. 
![rviz_1](https://user-images.githubusercontent.com/16001211/66380223-45bfde80-e9b7-11e9-879e-28b64f50c107.png)

I tested the same sensor with the same configs on a Windows machine with PandarViewer (I used correction file which was provided by the USB disk), I was surprised about the quality of points.

![PandarView1](https://user-images.githubusercontent.com/16001211/66380511-e910f380-e9b7-11e9-8533-a3a3e173cd28.PNG)
![PandarView2](https://user-images.githubusercontent.com/16001211/66380513-e910f380-e9b7-11e9-8364-0c0e0267ccac.PNG)

I couldn't find any setting to load the correction file into the ROS API, indeed? 

I founded two different API for Hesai (this one is linked on the Hesai Page, the another one is here: https://github.com/HesaiTechnology/HesaiLidar_PandarGeneral_ros). Which one is the right API?

**Comment by musti95** [comment]
We encountered the same problems with the Pandar40P and this package and decided to add a parameter for passing a correction file to the ros node. You can see the changes we made in this pull-request: #8

**Comment by hesaiwuxiaozhou** [comment]
We have merged your request. Thaks for submitting the code
